### ISSUE TITLE
Изменить рутовскую страницу 

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#103]
**Изменить рутовскую страничку**

**Конечный результат:** 

_При  входе либо регистрации рутовской страницей должна быть страница ввода номера телефона_

**План решения:** 

_Изменить рутовскую страницу с  **'authentication#login_or_signup'** на **'authentication/show_form', as: :show_form_in**
Удалить вьюху login_or_signup и метод ligin_or_signup в AuthenticationController_

**Мотивация:** 
_Заказчик хочет, чтобы стартовой страницей была форма ввода телефона_

**Критерии приёмки:**

_Если я зарегистрирован в системе:
захожу в приложение, ввожу свой телефон, меня перебрасывает на страничку ввода моего пароля_

_Если я не зарегистрирован в системе:
захожу в приложение, ввожу свой телефон, меня перебрасывает на страничку создание моего пароля, далее на создание никнейма_

**Планируемое время работы:** 30 минут

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#103 - Изменить рутовскую страничку](https://trello.com/c/JCyln6Om/12-task103-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B8%D1%82%D1%8C-%D1%80%D1%83%D1%82%D0%BE%D0%B2%D1%81%D0%BA%D1%83%D1%8E-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%BA%D1%83)

**Comment by sankhuan** [comment]
Начала работу в 23:48
