### ISSUE TITLE
При загрузке новостной ленты пользователь добавляется к себе в подписчики и подписки

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#105]
**При загрузке новостной ленты пользователь добавляется к себе в подписчики и подписки столько раз, сколь загружал эту страницу**
**Шаги воспроизведения:**
_Пользователь заходит на новостную ленту, далее заходит к себе на страничку_

**Наблюдаемое поведение:** 

_он появляется у себя в подписках и подписчиках_

**Ожидаемое поведение:**

_Пользователь не должен появляться у себя в подписках при загрузке новостной ленты_

**Причины**: 
_Дело в том, что оказалось, что метод вывода постов подписчиков месте с постами пользователя работает не правильно, он выводит посты, но так же добавляет самого себя в подписчики и подписки._

**Вариант решения:** 

_Нужно изменить этот метод_

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#105 - При загрузке новостной ленты пользователь добавляется к себе в подписчики и подписки](https://trello.com/c/XKU614i9/14-task105-%D0%BF%D1%80%D0%B8-%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B5-%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%BD%D0%BE%D0%B9-%D0%BB%D0%B5%D0%BD%D1%82%D1%8B-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%D1%81%D1%8F-%D0%BA-%D1%81%D0%B5%D0%B1%D0%B5-%D0%B2-%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%87%D0%B8%D0%BA%D0%B8-%D0%B8-%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D0%BA%D0%B8)

**Comment by sankhuan** [comment]
Начала работу в 00:15

**Comment by sankhuan** [comment]
Закончила работу в 19:08
На работу ушло 2 часа
