### ISSUE TITLE
Если юзер залогинен - то ему не доступна страница входа и регистрации

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#108]
**Если юзер зарегистрирован - то ему не доступна страница входа и регистрации**
**Шаги воспроизведения:**
_Пользователь заходит в свой профиль или регистрируется_

**Наблюдаемое поведение:** 

_он появляется на новостной ленте, но страница ввода телефона при входе, а так же создания или ввода пароля, создание никнейма ему так же доступна_

**Ожидаемое поведение:**

_Пользователь не должен суметь зайти на страницу регистрации/входа/создания пароля/ввода пароля/создания никнейма если его сессия открыта_

**Причины**: 
_Не хватает метода в контроллере, который проверяет, что пользователь уже в системе_

**Вариант решения:** 

_Добавить метод  в ApplicationController с условием - если user_signed_in? - то перенаправляется на новостную ленту,  и добавить before_action в AuthenticationController _

**Время на выполнения тикета:** 30 минут

**Comment by sankhuan** [comment]
начала работу в 16:20

**Comment by sankhuan** [comment]
Закончила работу в 17:40 
на работу ушло 30 минут
