### ISSUE TITLE
Валидация формы ввода телефона 

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#109]
**Валидация формы ввода телефона**
**Шаги воспроизведения:**
_Незарегистрированный либо незалогиненный пользователь заходит в наше приложение_

**Наблюдаемое поведение:** 

_он направляется на страницу ввода телефона и может ввести более 10 символов, а так же если введет менее 10 символов, он может нажать на кнопку продолжить и сможет зарегистрироваться с неправильным телефоном_

**Ожидаемое поведение:**

_Пользователь не может ввести более 10 символов, а так же если цифр меньше 10, то кнопка будет не активна, она становится активна только после того, как в форме ввода телефона 10 символов_

**Причины**: 
_Есть код js в файле authentication.js, но он не работает с первого раза загрузки страницы, только если перезагрузить страницу, то он начинает работать в форме ввода и не дает ввести больше 10 символов._

**Вариант решения:** 

_Необходимо изменить этот код, так как он работает не правильно и добавить на проверку количество символов - если цифр не 10, тогда кнопка продолжения не активна_

**Время на выполнения тикета:**

**Comment by sankhuan** [comment]
Начала работу: 17:52

**Comment by sankhuan** [comment]
Закончила в 19:00 
На работу ушло 1 час 18 минут
