### ISSUE TITLE
 Изменение метода входа в Devise

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#112]
**Изменение метода входа в Devise**
**Шаги воспроизведения:**
_Незалогиненый пользователь заходит в приложение, он видит страницу ввода телефона, вводит телефон и направляется на страницу ввода пароля_

**Наблюдаемое поведение:** 

_На этой странице он вводит свой пароль, если пароль не правильный, происходит редирект на эту же страницу, но телефон юзера теряется, и он не сможет зайти даже если введет правильный пароль_

**Ожидаемое поведение:**

_На этой странице он вводит свой пароль, если пароль не правильный, происходит редирект на эту же страницу, и теперь если он вобьет правильный пароль, то сможет войти_

**Причины**: 
_Мы добавили метод look_for в AuthenticationController, который создает (но пока не сохраняет) юзера  с паролем и передает его в контроллеры Devise. Но при редиректе(когда неправильно ввел пароль) этот юзер теряется_

**Вариант решения:** 

_ _

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task #112 Изменение метода входа в Devise](https://trello.com/c/e8lbBhZA/16-task-112-%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D0%B2-devise)

**Comment by sankhuan** [comment]
Начала работу в 18:55
Закончила в 23:08
На работу ушло 2 часа
