### ISSUE TITLE
Валидация формы создания пароля

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#114]
**Валидация формы создания пароля**
**Шаги воспроизведения:**
_Незарегистрированный пользователь после ввода телефона перенаправляется на страничку создания пароля_

**Наблюдаемое поведение:** 

_он вводит пароль, но валидация срабатывает только на длину - если 8 или более символов - то становится зеленой слово 8 символов, но не работает на цифры, так же он может и не вводить пароль, но сможет нажать на продолжить_

**Ожидаемое поведение:**

_Кнопка не будет активна, пока в пароле не будет хотя бы 8 символов и из них 1 цифра, так же валидация на проверку количества символов и одной цифры должна срабатывать как к мокапе - есть одна цифра - валидация окрасилась в  зеленый, пароль - более или равен 8 символов - валидация окрасилась в зеленый_

**Причины**: 
_Есть код js, но он работает только на проверку 8 символов в пароле._

**Вариант решения:** 

_Необходимо изменить этот код, так как он работает не правильно и добавить на проверку цифр, так же добавить проверку если символов не 8, и нет ни одной цифры, тогда кнопка продолжения не активна_

**Время на выполнения тикета:**

**Comment by sankhuan** [comment]
Начала работу в 22:30

**Comment by sankhuan** [comment]
Закончила работу в 22:30
На работу ушел 1 час
