### ISSUE TITLE
Валидация и проверка дублирования при создании никнейма

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#115]
**Валидация и проверка дублирования при создании никнейма**
**Шаги воспроизведения:**
_Незарегистрированный пользователь после ввода телефона и пароля перенаправляется на страничку создания никнейма_

**Наблюдаемое поведение:** 

_он вводит любой  никнейм либо не вводит его вообще и может нажать н а кнопку продолжить_

**Ожидаемое поведение:**

_Если никнейм не введен - кнопка должны быть не активна, если никнейм менее 5 символов - кнопка должна быть не активна, так же при нажатии на кнопку он проверяет, есть ли пользователь с таким никнеймом, если есть, то под полем ввода никнейма выводится сообщение - пользователь с таким никнеймом уже существует_

**Причины**: 
__

**Вариант решения:** 

__

**Время на выполнения тикета:**

**Comment by BuBuZa** [comment]
взял в разработку 21:20

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#115 Валидация и проверка дублирования при создании никнейма](https://trello.com/c/PSpIc3DI/17-task115-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8F-%D0%B8-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%B4%D1%83%D0%B1%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BF%D1%80%D0%B8-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B8-%D0%BD%D0%B8%D0%BA%D0%BD%D0%B5%D0%B9%D0%BC%D0%B0)

**Comment by BuBuZa** [comment]
закончил 20:45

**Comment by RenyVary** [comment]
Очень много времени(3 недели) ушло на понимание JavaScript
