### ISSUE TITLE
Навбар по мокапу

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#118]
**Переделать навбар по мокапу**
**Проблема:**

_Стили навбара в приложении не соответствуют стилям навбара в мокапе_

**Решение:**
_Изменить стили навбара по мокапу_

**Comment by RenyVary** [comment]
приступила во вторник в 12:10

**Comment by RenyVary** [comment]
закончила во вторник в 22:08
на работу ушло 3 часа 10мин
