### ISSUE TITLE
Создание комментариев с помощью js

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#120]
**Создание комментариев с помощью js**
**Шаги воспроизведения:**
_Пользователь заходит на страницу комментариев и пишет коментарий к посту и нажимает enter_

**Наблюдаемое поведение:** 

_страница обновляется и появляется его комментарий_

**Ожидаемое поведение:**

_страница не обновляется, а комментарий пользователя появляется_

**Причины**: 
__

**Вариант решения:** 
__

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#120 Создание комментариев с помощью js](https://trello.com/c/KZV26oPL/20-task120-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B5%D0%B2-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-js)

**Comment by RenyVary** [comment]
приняла в работу в четверг в 19:00

**Comment by RenyVary** [comment]
Закончила работу над заданием в 17:58 во вторник
