### ISSUE TITLE
Ответ на комментарий не открывает форму ввода коментария

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#121]
**Ответ на комментарий не открывает форму ввода комментария**
**Шаги воспроизведения:**
_Пользователь заходит на страницу поста и хочет добавить комментарий и комментарию_

**Наблюдаемое поведение:** 

_пользователь нажимает на ссылку ответить у самого первого комментария, открываются все формочки ввода у всех комментариев, если он нажмет на кнопку ответить у второго(либо любого другого, кроме первого) комментария, то формочка не откроется, а страница просто перезагрузится  _

**Ожидаемое поведение:**

_Пользователь нажимает на ссылку ответить у любого комментария, и вместо кнопки ответить, появляется форма ввода именно около того комментария, к которому пользователь хочет написать ответ_

**Причины**: 
_._

**Вариант решения:** 

_Нужно изменить этот метод_

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#121 Ответ на комментарий не открывает форму ввода коментария](https://trello.com/c/sAmFodhi/21-task121-%D0%BE%D1%82%D0%B2%D0%B5%D1%82-%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B9-%D0%BD%D0%B5-%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D0%B2%D0%B0%D0%B5%D1%82-%D1%84%D0%BE%D1%80%D0%BC%D1%83-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0-%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D1%8F)

**Comment by RenyVary** [comment]
исправлено в [#120](https://github.com/ESDPgroup3/tengri_social/issues/120)
