### ISSUE TITLE
Добавить в posts/index метод на вывод постов с последнего к первому

### ISSUE THREAD

**Issue by RenyVary** [ESDPgroup3/tengri_social#127]
**Посты выводятся в хронологическом порядке, а нужно чтобы было в обратном от последнего к первому**
**Шаги воспроизведения:**
_Пользователь заходит на страницу новостной ленты и видит посты_

**Наблюдаемое поведение:**

_пользователь на странице новостной ленты видит посты в хронологическом порядке _

**Ожидаемое поведение:**

_Пользователь на странице новостной ленты должен видеть посты в обратном хронологическом порядке от последнего к первому по времени создания поста_

**Причины**:
_у переменной @posts не прописано правило вывода в обратном порядке _

**Вариант решения:**

_Нужно добавить метод вывода массива в обратном порядке_

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task #127 Добавить в posts/index метод на вывод постов с последнего к первому](https://trello.com/c/nadP5n3y/22-task-127-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2-posts-index-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-%D0%BD%D0%B0-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4-%D0%BF%D0%BE%D1%81%D1%82%D0%BE%D0%B2-%D1%81-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B5%D0%B3%D0%BE-%D0%BA-%D0%BF%D0%B5%D1%80%D0%B2%D0%BE%D0%BC%D1%83)
