### ISSUE TITLE
оформить страницу создания нового поста - posts/new

### ISSUE THREAD

**Issue by RenyVary** [ESDPgroup3/tengri_social#128]
**Страница - posts/new еще не оформлена в соответствии с [мокапом](https://www.figma.com/file/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=186%3A244)**
**Шаги воспроизведения:**
_Пользователь заходит на страницу создания нового поста_

**Наблюдаемое поведение:**

_пользователь видит страницу с с формой ввода заголовка и описания также кнопку прикрепления файла и кнопку отправки_

**Ожидаемое поведение:**

_пользователь видит страницу с плейсхолдером: "Начните писать тут" и внизу иконки для добавления фотографии и видео + не активную кнопку_

**Причины**:
_._

**Вариант решения:**

_Пока только удалить поле заголовка, прописать стили для  поля описание и для кнопок_

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task #128 Оформить страницу создания нового поста - posts/new](https://trello.com/c/d93qGDVg/23-task-128-%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D1%81%D1%82%D0%B0-posts-new)

**Comment by RenyVary** [comment]
Марина прописала стили для странице в [135 ](https://github.com/ESDPgroup3/tengri_social/issues/135)

**Comment by RenyVary** [comment]
Марина прописала стили для страницы в 135 ветке но есть еще доработки по выводу кнопок добавления картинки и видео
