### ISSUE TITLE
На странице новостной ленты исправить стиль для не активного пользователя

### ISSUE THREAD

**Issue by RenyVary** [ESDPgroup3/tengri_social#129]
**Стиль для не активного пользователя горит красным **
**Шаги воспроизведения:**
_Пользователь заходит на страницу новостной ленты и не видит у неактивных никакого кружочка_

**Наблюдаемое поведение:**

_пользователь на странице пользователя видит у всех пользователей зеленый кружочек _

**Ожидаемое поведение:**

_Пользователь заходит на страницу новостной ленты и не видит у неактивных никакого кружочка, только у активных пользователей должен быть зеленый кружочек_

**Причины**:
_Забыла заменить current_user.online? на post.user.online? и не прописала стиль color:transparent для неактивного fa fa-circle_

**Вариант решения:**

_Нужно заменить current_user.online? на post.user.online? и  прописать стиль color:transparent для неактивного fa fa-circle_

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task #129 На странице новостной ленты исправить стиль для не активного пользователя](https://trello.com/c/Y52eIfuA/24-task-129-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%BD%D0%BE%D0%B9-%D0%BB%D0%B5%D0%BD%D1%82%D1%8B-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D1%82%D0%B8%D0%BB%D1%8C-%D0%B4%D0%BB%D1%8F-%D0%BD%D0%B5-%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)

**Comment by BuBuZa** [comment]
взял в разработку 21:50

**Comment by BuBuZa** [comment]
Закончил 21:40
