### ISSUE TITLE
Сделать стили в настройках страницы пользователя

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#133]
** На странице редактирования страницы исправить стили **
### Шаги воспроизведения:
Пользователь заходит на страницу редактирования страницы и видит ее дизайн согласно мокапу

### Наблюдаемое поведение:
Страница редактирования пользователя не соотвествует мокапу 

### Ожидаемое поведение:
Верстка страницы должна выглядеть так, как есть в мокапе

### Причины:
Видимо была изменена верстка во вью данной страницы

### Вариант решения:
Прописать верстку во view 

### Время на выполнение тикета:

**Comment by tm20388** [comment]
начала работу в 22 00
закончила в 01 00
