### ISSUE TITLE
Страница подписчиков и подписок по мокапу

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#141]
**Страница подписчиков и подписок по мокапу**
**Шаги воспроизведения:**
_Пользователь заходит на страницу со списком своих подписчиков или подписок_

**Наблюдаемое поведение:** 

_страница не отображается как по мокапу _

**Ожидаемое поведение:**

__

**Причины**: 
_Необходимо добавить стили для этой странице _

**Вариант решения:** 

__

**Время на выполнения тикета:**

**Comment by BuBuZa** [comment]
Взял 21:10

**Comment by BuBuZa** [comment]
Закончил 21:40
