### ISSUE TITLE
Добавить поиск

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#143]
**Добавить поиск**
**Шаги воспроизведения:**
_Пользователь заходит на новостную ленту, нажимает на лупу_

**Наблюдаемое поведение:** 

_ и ничего не происходит_

**Ожидаемое поведение:**

_Пользователь переходит на страницу поиска, и у него выходит поиск с 4 вкладками - популярное, номера, люди и хэштеги, необходимо создать поиск по людям и пономерам_

**Причины**: 
_ _

**Вариант решения:** 

__

**Время на выполнения тикета:**

**Comment by RenyVary** [comment]
приняла в работу в четверг 14.03.2019 в 17:20
