### ISSUE TITLE
Добавить возможность сделать профиль приватным

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#144]
**Добавить возможность сделать профиль приватным**
**Шаги воспроизведения:**
_Пользователь заходит на в настройки своего профиля и нажимает на ссылку - сделать профиль приватным_

**Наблюдаемое поведение:** 

_ и ничего не происходит_

**Ожидаемое поведение:**

_ переключатель на страничке становится синим - значит профиль стал приватным_

**Причины**: 
_Дать пользователю возможность выбирать кто может просматривать его страницу _

**Вариант решения:** 

_ Добавить колонку к модели User - is_private?, если в настройках включена приватность, то в колонке true, если приватность отключена, то в колонке false_

**Время на выполнения тикета:**

**Comment by RenyVary** [comment]
приняла в работу в четверг в 19:00

**Comment by RenyVary** [comment]
закончила работу в пятницу в 21:45
