### ISSUE TITLE
Уточнение у пользователя, что он хочет отписаться

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#148]
**Уточнение у пользователя, что он хочет отписаться**
**Шаги воспроизведения:**
_Пользователь на странице друго пользователя, на которого он подписан, на странице подписчиков и подписок нажимает на кнопку отписать_

**Наблюдаемое поведение:** 

_отписывается от пользователя _

**Ожидаемое поведение:**

_выходит попап окно, в котором уточняется - вы точно хотите отписаться от пользователя
**Причины**: 
_ _

**Вариант решения:** 

__

**Время на выполнения тикета:**

**Comment by BuBuZa** [comment]
начал в 19:00

**Comment by BuBuZa** [comment]
закончил 22:00
