### ISSUE TITLE
Сделать верстку по мок апу для мобильной версий

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#156]
**Шаги воспроизведения:**
Написать стили для мобильной версий
**Наблюдаемое поведение:**
верстка ломается

**Ожидаемое поведение:**
по мок апу
**Причины**:
_ _

**Вариант решения:**
Написать стили css для моб версий
__

**Время на выполнения тикета:**

**Comment by tm20388** [comment]
начала работу 5 марта в 19 00
закончила 10 марта в 23 00
ушло на работу 6 часов
