### ISSUE TITLE
Уточнение у пользователя, что он хочет отписаться

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#157]
**Шаги воспроизведения:**
на станице подписчики добавить уточнение если пользователь хочет отписаться
добавить в модальное окно имя пользователя от которого хотите отписаться
**Наблюдаемое поведение:**
при нажатий на отписаться если пользователь подписан на данного пользователя то выходит модальное окно с выбором отписаться или отмена.

**Ожидаемое поведение:**

_выходит попап окно, в котором уточняется - вы точно хотите отписаться от пользователя имя пользователя(никнейм)
**Причины**:
_ _

**Вариант решения:**
написать условие во вьюхе index.html
__

**Время на выполнения тикета:**

**Comment by sankhuan** [comment]
приняла в работу во вторник 05.03.19 в 17:30 
закрыла во вторник 05.03.19 в 19:32
