### ISSUE TITLE
Редактировать и удалять посты

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#32]
Описание: каждый пользователь может удалять и редактировать только свои записи 
Предыстория: пользователь имеет возможность добавлять записи, но их редактирование и удаление так же необходимо.
Сама задача: добавить в контроллер методы delete & edit & update , показать пользователю, что он имеет такую возможность, то-есть вывести их как кнопки/ссылки после каждого поста пользователя.
Метод решения: Организовать роутинг , создать методы в контроллере, сверстать соответствующие view для каждого метода,сделать проверку на current user, вывести кнопки/ссылки после каждого поста. 
Сценарий приемочного тестирования: 
авторизованный пользователь попытается нажать на ссылку удаления, пост удаляется и пользователь видит только остальные посты (страница на которой будет находиться пользователь не должна обновляться) (пользователь может удалять свои посты со своей страницы или же с основной ленты) 
авторизованный пользователь не видит ссылки удаления/редактирования не на своих постах
авторизованный пользователь нажимает на кнопку редактирования поста и видит форму редактирования поста (редактирование фотографии тоже должно быть), после того как пользователь отредактировал пост, он нажимает на кнопку update и его выбрасывает обратно на страницу где он был. 
Предполагаемое время выполнения тикета:  2 часа

**Comment by tm20388** [comment]
начала работу в 18 13

**Comment by tm20388** [comment]
закончила работу в 20 00

**Comment by tm20388** [comment]
на работу ушло 1 час 40 минут
