### ISSUE TITLE
Возможность удалять и редактировать комментарии

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#35]
Описание: пользователь может редактировать и удалять свои комментарии
 
Предыстория: После того как пользователь добавил комментарий, появляется возможность редактировать и удалять его. Только авторизованный пользователь может удалять и редактировать СВОИ комментрии

Сама задача: добавить в контроллер методы delete & update & edit
Метод решения: прописать методы в контроллер, добавить view , вывести ссылки после каждого комментария. Сделать проверку на current user 

Сценарий примерочного тестирования: 
пользователь добавляет комментарий и тут же решает его редактировать или удалить. Если пользователь решил редактировать, то пользователь все еще находится на той же странице. Форма редактирования очень схожа с формой создания, остается только нажать на submit. Когда же комментарий удаляется страница точно так же не обновляется.

Планируемое время работы:

**Comment by BuBuZa** [comment]
приступил к работе в 20:20 планируемое время работы 40мин

**Comment by RenyVary** [comment]
По мокапу заказчика удалять комментарии не нужно
