### ISSUE TITLE
Создать Followers

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#38]
Описание: дать возможность пользователям follow-ить друг-друга
Предыстория: пользователи могут взаимодействовать друг с другом. Добавлять друг-друга в друзья.
Сама задача: создать связи многие ко многим
Метод решения: сгенерировать модель Followers в которой присутствуют поле с id пользователей. Создать контроллер Followers. Прописать view. Вывести на страницы пользователей кнопки подписки
Сценарий приемочного тестирования:
если пользователь заходит на свою страницу на ней имеется 2 кнопки подписок и подписчиков, проходя по ним пользователь видит подписанных на него пользователей и подписки пользователя. 
На странице других пользователей должна иметься кнопка показывающая подписан ли пользователь или нет. 
Предполагаемое время выполнения тикета:

**Comment by tm20388** [comment]
Предполагаемое время выполнения тикета: 3 часа
Начала работу в 16 15

**Comment by tm20388** [comment]
закончила работу в 17 22
Ушло времени 1 час 5 минут
Изначально работа показалась сложной, поэтому предположила что буду делать ее 3 часа.
