### ISSUE TITLE
Создать валидации и вывести ошибки валидации 

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#40]
Описание: валидация на ввод одинаковых паролей, заполнение постов и регистрации. 
Предыстория: не позволять пользователям авторизироваться без валидного логин и пароля. Не позволять пользователям писать посты без валидного содержания. Позволить пользователям видеть ошибки валидации, чтобы понять в чем дело 
Сама задача: решить проблему невалидных значений 
Метод решения: прописать валидацию в модели и ошибки в application view
Сценарий приемочного тестирования: если пользователь попытается ввести невалидный номер ( например больше 11 цифр )
то выше заполненной формы высветиться ошибка валидации
иначе пользователь не сможет перейти к заполнению следующей формы. 
Если пользователь попробует ввести несколько разных паролей
то выше заполненной формы высветиться ошибка валидации
иначе пользователь не сможет перейти к своей странице 
Если пользователь попытается ввести в новый пост больше символов, чем положено 
то выше заполненной формы высветиться ошибка валидации

Время на выполнение тикета:

**Comment by tm20388** [comment]
Время на выполнение тикета: 1 час 30 минут
начала работу в 17 36

**Comment by tm20388** [comment]
Не получается сделать валидацию для ввода телефона, так как изначально мы не работаем с моделью юзера.  Скорее всего необходимо сделать валидацию с помощью  javascript, но есть такая возможность, что регистрация и вход для пользователя будет изменена.  Считаю что лучше будет этот тикет оставить на исполнение позже.

**Comment by tm20388** [comment]
закончила работу над тикетом в 20 10 на слудеющий день. ушла на работу 40 минут. Тикет не закончен

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#40 - Валидации и вывести ошибки валидации](https://trello.com/c/SeDrYajB/10-task40-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8-%D0%B8-%D0%B2%D1%8B%D0%B2%D0%B5%D1%81%D1%82%D0%B8-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D0%B8)
