### ISSUE TITLE
Показ подписчиков и подписок у других пользователей 

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#43]
Описание: каждый пользователь может видеть подписки и подписчиков других пользователей на их стене 
Сама задача: позволить пользователям просматривать подписки других пользователей
Метод решения: обновить view 
Сценарий приемочного тестирования: 
если пользователь заходит на страницы других пользователей 
то по клику на кнопку он видит список подписанных пользователей или список подписок пользователя
Предполагаемое время выполнения тикета: 1 час

**Comment by tm20388** [comment]
Начала доработку тикета в 16 00
добавила на страничке новостной летны просмотр постов только тех пользователей, на которых подписан
Закончила в 16 40
на работу ушло 40 минут
