### ISSUE TITLE
Аватары пользователей

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#44]
Описание: пользователи могут добавлять аватар на свою страницу, фото видят все пользователи 
Предыстория: пользователь имеет возможность добавлять аватар, но редактирование и удаление так же необходимо.
Сама задача: прописать active storage не только в ленту, но и в пользователя
Метод решения: обновить controllers & view пользователя 
Сценарий приемочного тестирования:
если пользователь пролистывает ленту
то он видит пользователей с аватором согласно с мокапом
если пользователь заходит на страницу он видит свою страницу с аватаром согласно мокапу 
мокапы здесь: https://www.figma.com/file/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?redirected=1
Предполагаемое время на выполнение тикета: 2 часа

**Comment by tm20388** [comment]
начала работа в 22 00

**Comment by tm20388** [comment]
закончила работу в 23 55
Ушла на выполнение тикета 1 час 55 минут

**Comment by tm20388** [comment]
не закончила работу, не сделала вывод аватарок на новостной ленте
начала  доработку в 15 52

**Comment by tm20388** [comment]
закончила доработку в 16 00
