### ISSUE TITLE
Создать модель Likes 

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#45]
Описание: каждый пользователь может ставить лайки на посты всех пользователей 
Предыстория: эта модель будет хранить в себе колличество лайков 
Сама задача: связать модели User, Likes, Post
Метод решения: создание модели ,  которая принимает post_id , user_id
Приемочное тестирование: проверка кода
Предполагаемое время выполнения тикета: 30 минут

**Comment by tm20388** [comment]
Начала работу в 20:20

**Comment by tm20388** [comment]
закончила работу в 20 50
Ушло время на выполнения тикета 30 минут
