### ISSUE TITLE
Создать контроллер Likes

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#46]
Описание: каждый пользователь может ставить лайки на посты всех пользователей
Предыстория: дать возможность пользователю ставить лайки, видеть количество лайков 
Сама задача: вывести кнопку лайк после каждого поста 
Метод решения: создать controller прописать view
Премочное тестирование: 
если пользователь ждет кнопку лайк, 
то количество лайков возрастает
Предполагаемое время выполнения тикета: 1 час 30 минут

**Comment by tm20388** [comment]
начала работу в 20 55

**Comment by tm20388** [comment]
закончила работу в 21 55
на выполнения тикета ушел 1 час
