### ISSUE TITLE
Создать главную страницу для входа

### ISSUE THREAD

**Issue by RenyVary** [ESDPgroup3/tengri_social#5]
Предыстория: 
Необходимо создать стартовую страницу где пользователь будет вводить номер телефона и в случае когда введенный номер существует в базе данных, предлагает ввести пароль, иначе предлагает создать пароль для нового аккаунта.
Задача:

1. Создать контроллер Authentication, добавить action "show_form_number" - мотод должен показывать форму с полем ввода номера телефона и кнопкой для отправки данных. 
Action "find_param" - метод должен принимать номер телефона, проверять существует ли в базе User с данным номером телефона
- если существует, то отправлять на страницу входа (sessions#new)
- если нет, то отправлять на страницу регистрации (registrations#new)
(не забывайте, всегда можно создать дополнительный метод для выноса сложной логики)

2. Создать View-ху "show_form_number" для стартовой страницы с формой запроса номера телефона

3. прописать маршруты в роутинге.

Ожидаемое время работы - 4 часа

**Comment by sankhuan** [comment]
начала работу в 20:54

**Comment by sankhuan** [comment]
закончила в 22:02
