### ISSUE TITLE
Дизайн на страницу ленты и мобилная верстка

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#63]
Описание: оформить дизайн ленты
Предыстория: 
Сама задача: прописать дизайн согласно мокапу
Метод решения: соответствие мокапу
мокап тут: https://www.figma.com/file/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=186%3A244 
Сценарий приемочного тестирования: если пользователь заходит на страницу ленты, то видит то же самое, что и в мокапе
Примерное время выполнение тикета:

**Comment by RenyVary** [comment]
приступила к работе в субботу в 19:15

**Comment by RenyVary** [comment]
закончила в понедельник 18:59
