### ISSUE TITLE
Ссылка на на страницу пользователя 

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#64]
Описание: в новостной ленте вывести ссылку на страницу пользователя 
Предыстория: возможность перейти с новостной ленты на страницу пользователя 
Сама задача: добавить на новостной ленте ссылку на переход к странице пользователя 
Метод решения: обновить view новостной ленты согласно мокапу 
мокап тут: https://www.figma.com/file/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=186%3A244
Сценарий приемочного тестирования: 
если пользователь пройдя регистрацию, попадает на новосную ленту
то он видит ссылку на переход к своей странице 
Примерное время на выполнение тикета:  45 минут

**Comment by tm20388** [comment]
Начала работу в 17 15

**Comment by tm20388** [comment]
закончила работу в 17 44
ушло времени 30 минут
