### ISSUE TITLE
Bootstrap > 4.1.2

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#65]
Описание: обновить версию Bootsrap 
Сама задача: обеспечить приложение версией bootstrap выше или равную версии 4.1.2
Метод решения: обновить файл Gemfile 
Сценарий приемочного тестирования: в GitHub не должно быть сообщения о опасности версии
Примерное время выполнения тикета:

**Comment by BuBuZa** [comment]
приступил к работе в 18:54
