### ISSUE TITLE
Выводит посты пользователя и тех на кого он подписан в новостной ленте

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#66]
Описание: посты пользователя в ленте
Сама задача: пользователь должен видеть свои посты в новостной ленте тоже
Метод решения: обновить view страницы ленты 
Сценарий приемочного тестирования: 
если пользователь заходит на страницу новостной ленты
то он видит и свои посты тоже
Примерное время на выполнение тикета:

**Comment by tm20388** [comment]
Начала работу в 20 30
закончила в 22 05
ушла на работу 1 час 35 минут
