### ISSUE TITLE
Дизайн профиля

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#67]
Описание: оформить дизайн профиля
Предыстория:
Сама задача: прописать дизайн согласно мокапу
Метод решения: соответствие мокапу
мокап тут: https://www.figma.com/file/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=186%3A244
Сценарий приемочного тестирования: если пользователь заходит на страницу своего профиля, то видит то же самое, что и в мокапе
Примерное время выполнение тикета:

**Comment by BuBuZa** [comment]
Закончил с перерывами 21.01.2019 в 22:00
