### ISSUE TITLE
Дизайн регистрации 

### ISSUE THREAD

**Issue by sankhuan** [ESDPgroup3/tengri_social#68]
Описание: оформить дизайн регистрации
Предыстория:
Сама задача: прописать дизайн согласно мокапу
Метод решения: соответствие мокапу
мокап тут: https://www.figma.com/file/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=186%3A244
Сценарий приемочного тестирования: если пользователь заходит на страницу регистрации, то видит то же самое, что и в мокапе
Примерное время выполнение тикета: 2 часа 30 минут

**Comment by tm20388** [comment]
начала работу в 17 50

**Comment by tm20388** [comment]
закончила в 16 45
ушла на работу 4 часа, в основном много времени ушло на javascript
