### ISSUE TITLE
исправление стилей на странице юзера и мобильная верстка

### ISSUE THREAD

**Issue by tm20388** [ESDPgroup3/tengri_social#81]
**Описание:** подправить на странице пользователя стиль. Сделать адаптивную под мобильную версию.  Сделать по мок апу.
**Предыстория:** зарегистрированный пользователь может зайти на свою страницу/профиль посмотреть и добавить свои посты. Так же он может отредактировать свои аккаунт, добавить, сменить аватарку. Изменить добавленный пост. 
**Сама задача:** Нужно исправить верстку страницы пользователя. Новые посты добавляются криво. Смещаются лесенкой влево. Доработать группу кнопок "подписчики", "подписки", "бонусов" добавить соответствующие иконки. Создать нав бар с надписью по середине "Профиль" и возможность вернутся назад.  Делать согласно примеру из мок апа:
https://www.figma.com/proto/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=216%3A10374&scaling=scale-down&redirected=1
**Метод решения:** во views user найти проблему. Возможно где то не закрытый тег. В группе кнопок можно использовать флексы для выравнивания иконок и надписей по середине.
**Сценарии приемочного тестирования:**
Если зарегистрированный пользователь у себя в профиле  нажимает на "добавить новый пост" то его перенаправляют на posts/new где пользователь заполняет title (который не нужен, но по валидаций нужно обязательно заполнять) и description. Добавить файл/картинку.
Пост добавляется на страницу пользователя. 
На странице пользователя все кнопки должны функционировать. 
Все посты должны добавляться в столбик. 
Последний добавленный пост должен отображаться в первым сверху.
Страница должна сужаться под мобильную версию при этом не искривляться. 
**Планируемое время работы:**

**Comment by RenyVary** [comment]
приступила во вторник в 21:30

**Comment by RenyVary** [comment]
закончила в субботу в 19:10
 очень много времени потратила на поиск решений о исправлении размера инпута, затем столкнулась с нечитаемостью вьюпорта с аппликейшн, да и сами стили подбирать не так быстро как думала.

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#40 - Исправление стилей на странице юзера и мобильная верстка](https://trello.com/c/yHcRkHYT/11-task40-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%B8%D0%BB%D0%B5%D0%B9-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D1%8E%D0%B7%D0%B5%D1%80%D0%B0-%D0%B8-%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0)

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#81 - Исправление стилей на странице юзера и мобильная верстка](https://trello.com/c/yHcRkHYT/11-task81-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%B8%D0%BB%D0%B5%D0%B9-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D1%8E%D0%B7%D0%B5%D1%80%D0%B0-%D0%B8-%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0)
