### ISSUE TITLE
Ответ пользователя на комментарий к посту.

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#82]
**Описание:** нужно сделать новую страницу, чат между пользователями на странице пользователя, его поста. Другой пользователь может комментить/ответить на посту пользователя. 
**Предыстория:** Пользователь может сделать новый пост с описанием. Другой пользователь может нажать на  ответить,  (идет переход на страницу чата и всех комментариев. Всплывает снизу клавиатура) Пользователь набирает текст и оставляет комментарий. Комментарий появляется у поста пользователя.
**Сама задача:** У одного поста может быть много комментариев разных пользователей. Делать по мок апу. https://www.figma.com/proto/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=216%3A8645&scaling=scale-down&redirected=1
**Метод решения**:  прописать новую связь между пользователями и комментариями. Создать новую вьюху для чата. см. мок ап стр.26. в comment_controller`e написать метод чтобы на комментарий можно было оставлять комментарий.
**Сценарий приемочного тестирования:** 
Когда пользователь нажимает ответить: Его перенаправляют на страницу чата типа: post_chat.html.erb где пользователь набирает текст/комментарий. По кнопке отправить или enter на клавиатуре коммент сохраняется у поста пользователя.
**Планируемое время работы:**

**Comment by tm20388** [comment]
Время на  выполнения тикета - 3 часа 30 минут
начала работу в 17 51

**Comment by tm20388** [comment]
закончила работу в 22 00
ушло на выполнения тикета 4 часа 30 минут

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#82 Ответ пользователя на комментарий к посту](https://trello.com/c/9J2YH7JK/9-task82-%D0%BE%D1%82%D0%B2%D0%B5%D1%82-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B9-%D0%BA-%D0%BF%D0%BE%D1%81%D1%82%D1%83)
