### ISSUE TITLE
Возможность добавления видео при создании поста

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#83]
**Описание:** Возможность добавления видео при создании поста
Предыстория: При созданий поста, пользователь, может загрузить к себе на страницу только картинку. 
**Сама задача:** Пользователь может добавить к своему посту картинку и видео файл. Добавить стили. По мок апу: https://www.figma.com/proto/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=216%3A8264&scaling=scale-down&redirected=1 
**Метод решения:** Изменить название файла, который прикрепляется к посту с picture на attachment. написать метод upload_attachment в контроллере, добавить куда нужно чтобы можно было загружать и сохранять файлы. В модели Post добавить has_one_attached :attachment
Во вьюхах внести поле ввода :attachment
**Сценарии приемочного тестирования:**
Пользователь, у себя на странице нажимает на "добавить новый пост" переходит на posts/new пользователь, вводит описание о чем видео, нажимает на добавить файл. Переход :attachment. Может выбрать picture или видео формат файла. А может выбрать  и добавить картинки и видео. Новый пост сохраняется на станице пользователя user/id
**Планируемое время работы:**

**Comment by tm20388** [comment]
Время на выполнен я тикета 2 часа
Начала работу в 15 30
