### ISSUE TITLE
переделать edit у userа дизайн по мок апу + моб. версию

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#84]
**Описание:** Переделать страницу редактирования пользователя
**Предыстория:** Пользователь через свои профайл может зайти в настройки и отредактировать свои данные. 
**Сама задача:** Переделать вьюху edit. Сделать согласно мок апу. 
https://www.figma.com/proto/J7CZqvEEIbH3YIGazPDNKFsr/social-concept?node-id=193%3A2287&scaling=scale-down&redirected=1
убрать поле title. Пользователь может изменить только никнейм.  Добавить раздел "Сбросить пароль" и "удалить аккаунт".
Страница должна быть адаптивная для мобильной версий.
**Метод решения:** во вьюхе devise/registration edit.html.erb убрать все кроме nickname и удалить аккаунт. Оформить согласно мок апу.
**Сценарии приемочного тестирования:**
В профиле сверху иконка настройка при нажатий переходим на страницу редактирования edit.html.erb 
Пользователь может поменять свои никнейм и нажать на сохранить изменения. После чего его перебрасывает обратно на страницу пользователя.
функцию Сбросить пароль сделать в другом тикете. Надо создать отдельную выплывающую страницу где пользователь вводит новый пароль и подтверждение пароля.
Если удалить аккаунт, то на root
Если нажать на выход,. то перебросить на страницу создания аккаунта authentication/show_form
**Планируемое время работы:**

**Comment by tm20388** [comment]
начала работу в 23 15

**Comment by tm20388** [comment]
закончила работу в 18 00
ушла на выполнение тикета 2 часа 30 минут
