### ISSUE TITLE
добавление статуса онлайн в профайле пользователя

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#85]
**Описание:** добавление статуса онлайн в профайле пользователя
**Предыстория:** Когда пользователь входит в свой аккаунт или аккаунт других пользователей видит зеленый кружочек возле аватарки пользователя, это значит пользователь онлайн на сайте. Если пользователя нет в системе в данный момент, то кружечек красный.
**Сама задача:** Сверстать страницу пользователя, добавить кружочек к аватарке. По мок апу
**Метод решения:** Написать метод типа user_online. Который принимает параметры сессий. Мог определять, когда пользователь зашел в систему и когда вышел. Прописать так же если user вышел из сессий, то заменить зеленый кружочек на красный. Написать лучше javascript`ом. 
**Сценарий приемочного тестирования:** 
При регистраций и входа в систему начинается сессия пользователя. срабатывает Метод считывания сессий. Пользователю применяется статус онлайн. Это изображается во вьюхе пользователя зеленым кружочком. 
Когда пользователь на своей странице или на странице других пользователей users/id  видит статус online или offline. Если пользователь закрыл или находится на сайте и бездействует больше 30 минут, то пользователь автоматический offline.
**Планируемое время работы:** 1 час 30 минут

**Comment by tm20388** [comment]
начала работу в 16 15

**Comment by tm20388** [comment]
закончила работу в 17 36
ушло на работу 1 час 20 минут

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [добавление статуса онлайн в профайле пользователя](https://trello.com/c/Oo2vxnY0/2-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%B0-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D0%B2-%D0%BF%D1%80%D0%BE%D1%84%D0%B0%D0%B9%D0%BB%D0%B5-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)
