### ISSUE TITLE
выводилось время и число когда создан пост

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#87]
Описание: Время и число у поста на странице пользователя.
Предыстория: Этот тикет сделан в тикете task#81

**Comment by tm20388** [comment]
Время на выполнения тикета - 30 минут
Начала работу в 17 40

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#87 - Выводить время и число когда создан пост](https://trello.com/c/zpPrHrlZ/8-task87-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D1%8C-%D0%B2%D1%80%D0%B5%D0%BC%D1%8F-%D0%B8-%D1%87%D0%B8%D1%81%D0%BB%D0%BE-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD-%D0%BF%D0%BE%D1%81%D1%82)
