### ISSUE TITLE
пользователь может добавлять emoji, smile в комментариях

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#88]
**Описание**: пользователь может добавлять emoji, smile в комментария**х
Предыстория**: на Web. приложении когда пишешь коммент нет возможности вставлять смайлики, эмодзи.
**Сама задача:** нужно чтобы пользователи могли добавлять смайлики и эмодзи 
**Метод решения:** Нужно найти и установить гем.
В формах для заполнения комментария в инпутах вставить иконку. При нажатий на иконку появляется маленькое окошко с эмодзи и смайликами.
**Сценарий приемочного тестирования:**  
Когда пользователь у себя на странице отвечает другому пользователю может использовать смайлики. Так же иконка смайлики должна выводится везде где вводится текстовые сообщения. страницы: Users/id, /posts/, users/id/edit/
**Планируемое время работы:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#88 - Возможность добавлять emoji, smile в комментариях](https://trello.com/c/L8pVHlqU/7-task88-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-emoji-smile-%D0%B2-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D1%8F%D1%85)

**Comment by tm20388** [comment]
время на выполнения тикета 1 час
начала работу в 20 00
