### ISSUE TITLE
проверить весь проект через rubycop

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#91]
**Описание:** проверить код rubocop`ом
**Предыстория:** Rubocop — гем для Ruby, позволяющий проверить .rb файл на корректность синтаксиса.
**Сама задача:** проверить код проекта на корректность синтаксиса
**Метод решения:** Сначала установить гем gurad task#100 благодаря чему при каждом изменении .rb файла Rubocop проверяет его и выводит результат в консоль и в log/rubocop.log файл. 
**Сценарий приемочного тестирования:**
Чтобы увидеть все настройки, достаточно прогнать команду 
$ rubocop --auto-gen-config
Результаты
Что в итоге настроено? В данном проекте достаточно запустить отдельными процессами zeus и guard. После чего происходит следующее:
Автоматически поддерживается запущенный через zeus Rails сервер, который перезапускается при каждом изменении основных файлов настроек проекта
При каждом изменении Gemfile устанавливаются все гемы
При изменении любого файла с тестом прогоняется этот тест
При изменении любого файла контроллеров/моделей/либов/вьюх запускается связанный с ним тест, если такой имеется
Каждый измененный ruby файл проверяется на грамотность с помощью rubocop
При изменении любого javascript/coffeescript файла запускаются все jasmine тесты
При изменении любого файла миграции или seeds прогоняются все необходимые миграции
**Планируемое время работы:**

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#91 - rubycop](https://trello.com/c/SdqKkEor/5-task91-rubycop)

**Comment by RenyVary** [comment]
приступила к задаче во вторник в 19:20

**Comment by RenyVary** [comment]
закончила в среду в 1:00
