### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#92]

**Comment by tm20388** [comment]
время на выполнения тикета 2 часа
начала работу в 12 15

**Comment by tm20388** [comment]
закончила в 16 00, ушло на  работу 2 часа 30 минут

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task #92 - TDD](https://trello.com/c/LMY3ecLI/3-task-92-tdd)
