### ISSUE TITLE
переделать posts/show сделать по мок апу. + моб.версию

### ISSUE THREAD

**Issue by BuBuZa** [ESDPgroup3/tengri_social#93]

**Comment by RenyVary** [comment]
приступила к работе в субботу в 19:15

**Comment by tm20388** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Task#93 - vievs posts по мок апу. + моб.версию](https://trello.com/c/pSROz2CR/6-task93-vievs-posts-%D0%BF%D0%BE-%D0%BC%D0%BE%D0%BA-%D0%B0%D0%BF%D1%83-%D0%BC%D0%BE%D0%B1%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8E)

**Comment by RenyVary** [comment]
приступила в среду в 7:00

**Comment by RenyVary** [comment]
взяла задачу в среду в 20:34

**Comment by RenyVary** [comment]
закончила в понедельник в 22:04
